name: CI

on: [push, pull_request]

env:
  JULIA_PKG_SERVER:

jobs:
  test:
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['lts', '1']
        arch: [x64]
        os: [ubuntu-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v2
      - run: sudo apt-get update && sudo apt-get install -y xvfb mesa-utils libgl1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          prefix: xvfb-run -a
